### ISSUE TITLE
error running SHARP

### ISSUE THREAD

**Issue by haowulab** [shibiaowan/SHARP#1]
Dear Shibiao,

Thanks for making SHAPR available. 

I encounter the following error running the example. Could you help take a look? Many thanks.  

> res = SHARP(scExp)
-----------------------------------------------------------------------
Data info:
Number of cells: 479 
Number of genes: 20490 
-----------------------------------------------------------------------
Preprocessing:
Normalization...
Error in { : task 1 failed - "could not find function "get_CH""

**Comment by haowulab** [comment]
I did a little investigation. It seems "get_CH" function is from clues, but that package is no longer on CRAN. However, that function is still being called in get_opt_hclust.R and getrowColor.R, which produced the error.

**Comment by haowulab** [comment]
I had to install clues from old CRAN archive, and it works now.

**Comment by shibiaowan** [comment]
Dear Dr. Wu,

Thanks for your interest in SHARP. Yes, you are right. This problem was due to the archived "clue" package which was removed from CRAN. Now I have updated the SHARP package and this problem should be cleared when you install the updated version.

Please tell me if you come across any other problems when running SHARP. Thanks.

Best wishes,

Shibiao
